name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/jekyll-build-pages@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: actions/checkout@v4
      - run: actions/jekyll-build-pages@v1
      - run: actions/upload-pages-artifact@v3
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
