name: Deploy site

on:
  push:
    branches: [master]
  pull_request:
    branches: ["*"]

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git branch
      uses: actions/checkout@v3.0.0
    - name: Setup Node.js
      uses: actions/setup-node@v3.0.0
      with:
        node-version: '16'
    - run: npm install
    - name: Deploy site
      run: |
        npm run deploy -- -m "Deploy"
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
